#配置端口号
server:
  port: 8017
  #配置服务应用名称
spring:
  application:
    name: springboot-swagger
    #将自己注册到eurekaServer中
eureka:
  client:
    #http://localhost:8100/eureka是注册中心的地址
    service-url:
      defaultZone: http://127.0.0.1:8110/eureka/,http://127.0.0.1:8120/eureka/,http://127.0.0.1:8130/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:

    #暴露ip地址
    prefer-ip-address: true
