#配置端口号
server:
  port: 8010
  #配置服务应用名称
spring:
  application:
    name: springcloud2-member-custm
    #将自己注册到eurekaServer中
eureka:
  client:
    #http://localhost:8100/eureka是注册中心的地址
    service-url:
      defaultZone: http://127.0.0.1:8110/eureka/,http://127.0.0.1:8120/eureka/,http://127.0.0.1:8130/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    #自定义服务名称不实用cloud自己创建的
    instance-id: springcloud2-member-custm
    #暴露ip地址
    prefer-ip-address: true
#设置fegin客户端调用服务的超时时间
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000