
#服务名称(服务注册到eureka名称)
spring:
  application:
    name: springcloud-hystriy-prod
eureka:
  client:
    #将客户端注册进eureka服务列表内
    service-url:
      #http://localhost:8100/eureka为eurekaServer的地址
      defaultZone: http://127.0.0.1:8110/eureka/,http://127.0.0.1:8120/eureka/,http://127.0.0.1:8130/eureka/
    register-with-eureka: true
    fetch-registry: true
  #将自己注册到eurekaServer内
  #检索服务
  instance:
    #instance-id: member-pro  注意在集群得环境下最好不要设置他，因为注册到eureka中得名称相同了，cloud默认会找最后一个启动得服务
    prefer-ip-address: true

server:
  port: 8116
